name: A workflow for action
on: [push, pull_request] 

jobs:  
  build:    
    name: Run fibonacci action   
    runs-on: ubuntu-latest   
    steps: 
        - uses: actions/checkout@v1
        - uses: ./fibonacci     
        with:          
           N_INDEX: 9