name: A workflow for action
on: push 

jobs:  
  build:    
    name: Run fibonacci action   
    runs-on: ubuntu-latest   
    steps: 
        - uses: actions/checkout@v1
        - uses: ./Actions       
        with:          
           N_INDEX: 8